apiVersion: v1
kind: Service
metadata:
 name: static-website-service
spec:
 selector:
   app: static-website
 type: NodePort
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30007  # You can choose any available port between 30000-32767